apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-csi-pv
  namespace: test-csi-ns
  labels:
    name: test-csi-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  csi:
    nodePublishSecretRef:
      name: "mapr-ticket-secret"
      namespace: "test-csi-ns"
    driver: com.mapr.csi-kdf
    volumeHandle: test-csi-pv
    volumeAttributes:
      volumePath: "/csi-test"
      cluster: "ms1.choudary.mapr.net"
      cldbHosts: "10.163.169.18"
      securityType: "secure"
      platinum: "true"