apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-kubernetes
  labels:
    app: springboot-kubernetes
spec:                
  selector:         
    matchLabels:
      app: springboot-kubernetes
  replicas: 2
  template:
    metadata:
      labels:        
        app: springboot-kubernetes
    spec:
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: springboot-kubernetes-claim2

      containers:
        - name: springboot-kubernetes
          image: 10.163.168.91:443/choudary/springboot-kubernetes:1.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: persistent-volume
              mountPath: /pv/tmp