apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: springboot-kubernetes
  labels:
    app: springboot-kubernetes
spec:                
  selector:         
    matchLabels:
      app: springboot-kubernetes
  replicas: 2
  template:
    metadata:
      labels:        
        app: springboot-kubernetes
    spec:
      containers:
        - name: springboot-kubernetes
          image: 10.163.168.91:443/choudary/springboot-kubernetes:2.0
          ports:
            - containerPort: 8080