apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-kubernetes-claim2
  labels:
    app: springboot-kubernetes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi