apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  type: NodePort
  ports:
    - name: springboot-kubernetes-greeting
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:           
    app: springboot-kubernetes
