apiVersion: v1
kind: Service
metadata:
  name: ss-springboot-kubernetes
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"
spec:
  ports:
    - name: ss-springboot-kubernetes-greeting
      port: 88
      targetPort: 8080
      protocol: TCP
  selector:           
    app: ss-springboot-kubernetes
  type: NodePort